"""empty message

Revision ID: 7cd9d9b2a62e
Revises: 4c6ac1c2ac42
Create Date: 2022-09-29 11:54:30.672899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd9d9b2a62e'
down_revision = '4c6ac1c2ac42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('friend_connections')
    # op.alter_column('friends', 'from_user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('friends', 'to_user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friends', 'from_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('friend_connections',
    sa.Column('from_user_id', sa.INTEGER(), nullable=False),
    sa.Column('to_user_id', sa.INTEGER(), nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('from_user_id', 'to_user_id')
    )
    # ### end Alembic commands ###
